steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/ppteng",
        "-f",
        "backend/Dockerfile", # 指向子目录的 Dockerfile
        ".", # 上下文设为根目录
      ]

  # Temporary step to verify file structure
  - name: "gcr.io/cloud-builders/docker"
    args: ["run", "gcr.io/$PROJECT_ID/ppteng", "ls", "-R", "/app"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/ppteng"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "ppteng"
      - "--image"
      - "gcr.io/$PROJECT_ID/ppteng"
      - "--region"
      - "asia-east1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "GOOGLE_APPLICATION_CREDENTIALS=/app/backend/serviceAccountKey.json"

# --- 添加以下这段配置 ---
options:
  logging: CLOUD_LOGGING_ONLY
# -----------------------

images:
  - "gcr.io/$PROJECT_ID/ppteng"
